import './global.css';
import { Inter } from 'next/font/google';
import 'locomotive-scroll/dist/locomotive-scroll.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Welcome to eve-records',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-950 text-neutral-200 tracking-tighter py-40`}
      >
        {children}
      </body>
    </html>
  );
}
